### PR TITLE
Move flush_all() out from @async (#693)

### PR DESCRIPTION
**Pull request by d4n1elchen**
This pull request fixes (probably not) #693 

I think this problem should be related to #491 and #563. Previously there's an issue about when to send the idle message. At that time, the solution was adding a delay before sending the idle message. I think it's because of the delay, the code, together with flush_all(), was wrapped by @asnyc. That means the flush_all() won't be called right after message handler finish the jobs. I think that will cause unexpected flush for the following messages. So I move the flush_all() out from the @asnyc wrapping and remain everything being the same (also remove @vprintln I just added). Then everything looks fine. It works with IJULIA_DEBUG is either true or false.

And according to #563, the delay is no more needed and has been removed. I think the @async is also not needed. But I'm not sure about this so I keep it in the code.

### CODE REVIEW

**Comment by Datseris** [comment]
@d4n1elchen you god you!!!! This is LGTM!!! Works on Julia 0.7 and Windows 10! Not only that, but it also works from running `using IJulia(); notebook()` from within Julia!!!

YEAAAAAAAAAA

**Comment by d4n1elchen** [comment]
Hey, some bad news here. 😢 

After testing for a while, I found that if the streaming is long, it'll still get stuck.

**Comment by Datseris** [comment]
It also doesn't work when using a package that has to compile. :(

**Comment by stevengj** [comment]
Just get rid of the `@async` entirely.

Honestly, I think #693 is some kind of memory bug, perhaps in ZMQ.jl, perhaps in julia itself.  That's why it disappears and re-appears randomly when you add print messages and make other small unrelated changes.  So I doubt that this PR actually fixes the problem.   But it is still a good change to make.

**Comment by Datseris** [comment]
Steven is right. Turns out this simply "doesn't work" some random times... Even if packages are precompiled...

**Pull request merged**
