### PR TITLE
Fix the "dev" docs badge

### PR DESCRIPTION
**Pull request by DilumAluthge**
cc: @stevengj

### CODE REVIEW

**Comment by stevengj** [comment]
The `stable` link is also broken…

**Comment by DilumAluthge** [comment]
Yeah the stable link will not work until you have tagged a new release.

**Comment by DilumAluthge** [comment]
You'll need to merge https://github.com/JuliaLang/IJulia.jl/pull/943 before you register a new release.

**Comment by stevengj** [comment]
Tagged at https://github.com/JuliaRegistries/General/pull/19534

**Comment by DilumAluthge** [comment]
I'm temporarily blocking automerge on https://github.com/JuliaRegistries/General/pull/19534

If https://github.com/JuliaRegistries/General/pull/19534 is merged before https://github.com/JuliaLang/IJulia.jl/pull/943 is merged, it's possible that the tag will be created but the docs won't be built on that tag, which is an annoying situation to be in.

**Comment by DilumAluthge** [comment]
Whoops I should have said #944

**Pull request merged**
