### PR TITLE
Fix segfault on macos (#968): doing heart beat via async and ZMQ.jl

### LINKED ISSUE #968: IJulia kernel doesn't work for Julia 1.6 on macOS
I can't get the IJulia kernel to work when using Julia 1.6/master. Tried latest IJulia release and IJulia#master. The kernel either seems to not start all or die immediately.

Julia <= 1.5.3 kernels work just fine.

```Julia
julia> versioninfo()
Julia Version 1.6.0-DEV.1661
Commit 56dd7d71a7* (2020-12-04 13:18 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = subl
  JULIA_NUM_THREADS = 6
  JULIA_PROJECT = /Users/crstnbr/.julia/environments/base
  JULIA_DQMC = /Users/crstnbr/sciebo/codes/julia-sdw-dqmc
  JULIA_PKG_SERVER = pkg.julialang.org
```

kernel_issues

### PR DESCRIPTION
**Pull request by daviehh**
May fix #968. Instead of running the heart beat in a thread via `uv_thread_create`, just do the echo server in a new process.

### CODE REVIEW

**Comment by rgobbel** [comment]
This versions runs, though on my Macbook Pro running Catalina one Julia process keeps running after shutdown via control-C at the command line. It does shut down properly if done via the Shutdown Kernel command in the notebook.

**Comment by daviehh** [comment]
@rgobbel Thanks for confirming it runs.

As you noted in https://github.com/JuliaLang/IJulia.jl/issues/977, the lingering process with ctrl-c may a separate issue; 
this PR just fixes the ijulia not working with julia 1.6.0, issue #968 

Whereas, the #977 issue may be a different thing:
- quitting from jupyter from Shutdown Kernel command in the notebook and the process quits normally
- quitting by ctrl-c in terminal: by turning debugging on, it turns out both processes (the main ijulia process and the worker heartbeat process) actually correctly quits, but for some reason jupyter then decides to restart the kernel. you may notice that the pid of the julia processes is different from before the ctrl-c shutdown. Looks like the shutdown_reply did not get sent in
 https://github.com/JuliaLang/IJulia.jl/blob/2300ab9cc4c723f9fabec5ea9b0360870b898494/src/handlers.jl#L186-L189

**Comment by stevengj** [comment]
Won't using `addprocs` like this interfere with people doing multiprocessing?

**Comment by daviehh** [comment]
@stevengj thanks, good call! Well, since the echo server blocks, things like `@everywhere` or `pmap` would work, but it would interfere with e.g. hard-coded `@spawnat`, etc, and would expose the process in e.g. `workers()`

Alternatively, the new process could be launched with e.g. `@async run(`Base.julia_cmd() -e [...]`)`; and it could be terminated by sending the echo server a string other than "ping" (which is currently the heartbeat message)
[link](https://github.com/jupyter/jupyter_client/blob/dd89e2748129e457d01cfe38ff79ba65d835fa9e/jupyter_client/channels.py#L148-L151)

e.g. in the julia hearbeat server
```julia
while true
    msg = recv(sock, String)
    println(msg)
    if msg == "ping"
        send(sock, msg)
    else
        exit()
    end
end
```

one could then send e.g. "stop" to the channel upon quitting IJulia (either in the `shutdown_request` [function](https://github.com/JuliaLang/IJulia.jl/blob/2300ab9cc4c723f9fabec5ea9b0360870b898494/src/handlers.jl#L185) or registering an `atexit` [hook](https://docs.julialang.org/en/v1/base/base/#Base.atexit))

**Comment by stevengj** [comment]
Note also that the whole point of the heartbeat thread, as I understand it, is so that Jupyter can detect if the process dies, so handling it in a separate process seems like it defeats the point?

**Comment by daviehh** [comment]
Thanks for pointing that out, the latest commit now uses async to call send/recv from ZMQ.jl instead of uv_thread_create and not in a new process.

**Comment by stevengj** [comment]
async also won't work, because if you have a long-running computation in Julia that doesn't `yield` then Jupyter will think Julia has died and restart it.

**Pull request closed without merging**
