### PR TITLE
Create greet.yml to welcome first time contributor

### PR DESCRIPTION
**Pull request by logankilpatrick**

### CODE REVIEW

**Comment by logankilpatrick** [comment]
We have something very similar working here: https://github.com/JuliaLang/www.julialang.org/blob/master/.github/workflows/greet.yml

**Comment by fredrikekre** [comment]
It seems unnecessary to spend compute on this, in particular since (i) this repo has barely no traffic and (ii) you are already welcomed with this

> If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
> We use the GitHub issue tracker for bug reports and feature requests only.
> 
> If you're submitting a bug report, be sure to include as much relevant information as
> possible, including a minimal reproducible example and the output of `versioninfo()`.
> If you're experiencing a problem with a particular package, open an issue on that
> package's repository instead.
> 
> Thanks for contributing to the Julia project!

**Comment by logankilpatrick** [comment]
That's fair. It makes sense just for PR's then. Feel free to close this if you think that's the right course of action

**Comment by tk3369** [comment]
I was just about to suggest that we make a massive set of PR’s to every registered packages 😝

**Pull request closed without merging**
