### PR TITLE
Add kwarg julia_cmd to installkernel (to support JupyterHub with containers, etc.)

### PR DESCRIPTION
**Pull request by oschulz**
This PR makes it possible to specify a custom `julia` command via

```julia
installkernel(Julia, julia_cmd="my_custom_julia_start_script")
```

It also allows passing an array - this should be very helpful to people (like me :-) ) who often run Julia in Linux containers but may be forced (e.g. by using a site-wide JupyterHub) to have Jupyter running outside of the container.

For Docker, running

```julia
installkernel(
    "Julia via Docker",
    julia_cmd = [
        "docker", "run", "--rm", "--net=host",
        "--volume=/home/USERNAME/.local/share/jupyter:/home/USERNAME/.local/share/jupyter",
        "some-container", "/opt/julia-1.x/bin/julia"
    ]
)
```

from within a container instance now works - provided Docker has been set up in a way that supports things like this (e.g. the user is  "USERNAME" both inside and outside). I use Docker in this example because it's well known, though it is not necessarily the right runtime for such use cases (see below).

More and more scientific computing sites now offer JupyterHub instances and also support containers via runtimes like [Shifter](https://github.com/NERSC/shifter) or [Singularity](https://sylabs.io/)). Like with Docker, calling Julia ([or Python, for that matter](https://docs.nersc.gov/services/jupyter/#shifter-kernels-on-jupyter)) becomes a multi-part command (only simpler), e.g. `["shifter", "--image", "myimage", "/opt/julia/bin/julia"]`. This typically forces users to manually fiddle with their "kernel.json" files, which is inconvenient.

Having a `julia_cmd` kwarg (supporting both a simple string and a vectors of strings) should make life easier.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Perhaps it would be nicer to give this as a `Cmd`? Or at least support that too. You can get out the string array with `c.exec`.
````
julia> c = ```
       docker run
           --rm
           --net=host
           --volume=/home/USERNAME/.local/share/jupyter:/home/USERNAME/.local/share/jupyter
           some-container
           /opt/julia-1.x/bin/julia
       ```
`docker run --rm --net=host --volume=/home/USERNAME/.local/share/jupyter:/home/USERNAME/.local/share/jupyter some-container /opt/julia-1.x/bin/julia`

julia> c.exec
7-element Array{String,1}:
 "docker"
 "run"
 "--rm"
 "--net=host"
 "--volume=/home/USERNAME/.local/share/jupyter:/home/USERNAME/.local/share/jupyter"
 "some-container"
 "/opt/julia-1.x/bin/julia"
````

**Comment by oschulz** [comment]
> Perhaps it would be nicer to give this as a Cmd

I thought about that, but I thought it might look inconsistent with the `options` argument. But if there are no objections in that regard, using a `Cmd` would of course be more user-friendly.

**Comment by oschulz** [comment]
If we use `Cmd`, the cleanest solution might be not to support `String` and `AbstractVector{<:AbstractString}` as well, but `Cmd` only.

What would you guys prefer?

**Comment by stevengj** [comment]
I'm inclined to support `Cmd` only.

Also, probably just call the keyword argument `julia` rather than `julia_cmd`.

**Comment by fredrikekre** [comment]
> I thought about that, but I thought it might look inconsistent with the options argument.

Yea, perhaps the options argument should be `Cmd` too.

**Comment by oschulz** [comment]
@stevengj sounds good

**Comment by oschulz** [comment]
> Yea, perhaps the options argument should be Cmd too.

Wouldn't that be abusing `Cmd` a bit, though? Not having an actual command in front, I mean?

**Comment by oschulz** [comment]
Sorry, lost track of this for a bit. I've implemented the changes now, using `julia_cmd::Cmd`.

**Comment by oschulz** [comment]
Ok, now tests pass, too. :-)

**Comment by oschulz** [comment]
@fredrikekre, @stevengj , does this look good to you now?

**Review by fredrikekre — APPROVED** [review]
LGTM. Is it possible to add a test? Perhaps just run `installkernel` and check that it produces the output file you want?

**Comment by oschulz** [comment]
@fredrikekre, @stevengj , gentle bump regarding merge.

**Comment by oschulz** [comment]
Sorry for bumping this again, @stevengj, I know you guys are busy. I have some users who could really use this.

**Comment by stevengj** [comment]
LGTM, but as I commented above I would rather call the keyword `julia` rather than `julia_cmd`.

**Comment by oschulz** [comment]
> as I commented above I would rather call the keyword julia rather than julia_cmd.

**Comment by oschulz** [comment]
> as I commented above I would rather call the keyword julia rather than julia_cmd.

Oops, sorry @stevengj, I overlooked your comment. It's changed to `julia` now.

**Comment by oschulz** [comment]
Thanks!

**Pull request merged**
