### PR TITLE
Fix PDF render

### PR DESCRIPTION
**Pull request by jeremiahpslewis**
Fixes https://github.com/JuliaLang/IJulia.jl/issues/1035 alongside 

PR [#4188](https://github.com/JuliaPlots/Plots.jl/pull/4188) (which has been merged)

### CODE REVIEW

**Comment by jeremiahpslewis** [comment]
@fredrikekre Wanted to flag this as ready for review. :)

**Comment by stevengj** [comment]
Is display of PDF images well supported in Jupyter?

This issue https://github.com/jupyter/notebook/issues/3652 seems to indicate that it only works in certain browsers or with certain plug-ins installed.

**Comment by jeremiahpslewis** [comment]
I think you're right in pointing out there is a bit of a file type conflict here:

Per the issue you linked, browser support of PDFs is (potentially) incomplete.

But Latex workflows like quarto's use case which use Jupyter to build a document (but not display it in the browser) do not work well with SVGs and require the use of the PDF format for exporting / displaying vector graphics.

Right now, if you create a PDF document with R, Python, and Julia graphs via quarto, the Julia graph gets dumped out as a PNG and looks significantly pixelated, the other two languages (afaik) allow for PDF viz export and certainly lead to vector viz output in the PDF.

**Comment by travigd** [comment]
The Jupyter format defines cell outputs as a dict that contains multiple representations of an output (e.g., plot). The frontend (e.g., jupyterlab) chooses which of the formats its want to render (so only one is *shown* at a time, but the various formats are present in the notebook file).

IJulia tries to generate a representation for every MIME type it supports (which is what this PR is changing).

This is actually not the case for Plots.jl -- it actually does override `IJulia.display_dict`: https://github.com/JuliaPlots/Plots.jl/blob/b6d7bd82e6c029b8cbbafa756015670cb0ab0013/src/init.jl#L92, which is what (personally) I think Quarto should do.

**Comment by jeremiahpslewis** [comment]
@travigd Thanks for the nudge to investigate this further, the Plots.jl PR https://github.com/JuliaPlots/Plots.jl/pull/4188 solved the issue for Plots, so this isn't necessary.

And for Makie, turns out it's a one-liner which can be done on the Quarto side: `IJulia.register_mime(MIME("application/pdf"))` 🎉

**Comment by benz0li** [comment]
> This is actually not the case for Plots.jl

Is there a way to override this in `startup.jl`/`startup_ijulia.jl`? For

1.  `Python`, one may set `c.InlineBackend.figure_formats = {'svg', 'pdf'}` in `ipython_config.py`/`ipython_kernel_config.py`
1.  `R`, one may set `options(jupyter.plot_mimetypes = c('text/plain', 'image/svg+xml', 'application/pdf'))` in `Rprofile.site`

in order to output both `image/svg+xml` and `application/pdf` plot formats in the notebook file:

*  `image/svg+xml` for plot display in the browser
*  `application/pdf` for direct PDF conversion

ℹ️ With `application/pdf` plot format in the notebook file, `inkscape` is not required for PDF conversion using `nbconvert`.

**Pull request closed without merging**
