### PR TITLE
Prevent SIGINT from killing the kernel

### PR DESCRIPTION
**Pull request by darwindarak**
Clicking the Interrupt Kernel button is still causing the kernel to restart.  This PR implements the fix mentioned in #31 to match the change in how Julia handles interrupts (JuliaLang/julia@10c7d4e).

### CODE REVIEW

**Comment by garrison** [comment]
This fixes the issue for me.

**Comment by stevengj** [comment]
Thanks!  There needs to be a `VERSION > v"0.3"` check, however, since Julia 0.2 is still supported by IJulia.

**Comment by darwindarak** [comment]
Ok, added the check!

**Comment by stevengj** [comment]
Thanks!

**Pull request merged**
