### PR TITLE
Add `port` keyword argument to `notebook` and `jupyterlab`

### LINKED ISSUE #1105: Can't choose the port from where to spawining the server with `IJulia.notebook`
The only work around I found is to run the following command
```
$(julia --compile=min --project -e 'using IJulia; println(joinpath(IJulia.Conda.SCRIPTDIR, "jupyter"))') notebook --port="${PORT}"
```
where `${PORT}` is the desired port, but this feels less than ideal.

### PR DESCRIPTION
**Pull request by giordano**
My small JuliaCon'24 hackathon project.  Fix #1105.

### CODE REVIEW

**Comment by giordano** [comment]
Bump

**Comment by giordano** [comment]
Friendly monthly bump

**Comment by ViralBShah** [comment]
@giordano Perhaps merge this if good to go? I assume you have commit access.

**Review by MasonProtter — APPROVED** [review]
Looks good / useful to me.

**Pull request merged**
