### PR TITLE
Call message handlers with invokelatest on 0.6-rc1+

### PR DESCRIPTION
**Pull request by JobJob**
This is needed for Interact to work on 0.6

- [x] Fix REQUIRE for Compat after https://github.com/JuliaLang/Compat.jl/pull/359 is merged

### CODE REVIEW

**Comment by stevengj** [comment]
Compat v0.25.0 adds `invokelatest` (https://github.com/JuliaLang/Compat.jl/pull/352), so we can just use `invokelatest` unconditionally if you bump the Compat requirement.  (Similarly for other places where we currently call `eval`.)

**Comment by JobJob** [comment]
Ok, do you mind if I close this and leave that to you? Spent a long time down the rabbit hole fixing Reactive issues.

**Comment by JobJob** [comment]
Ok, updated this. Waiting on https://github.com/JuliaLang/Compat.jl/pull/359 (and a tag) so we can update the REQUIRE, otherwise this won't work on julia 0.5

**Comment by stevengj** [comment]
Thanks!

**Comment by JobJob** [comment]
Updated. Oh https://github.com/JuliaLang/METADATA.jl/pull/9334 wasn't merged yet in Metadata, causing test failures.

**Pull request merged**
